name: learn
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  fluttertoast: 
  dio: 
  permission_handler:
  downloads_path_provider_28:


  flutter_localizations: 
    sdk: flutter
  intl: 
  cupertino_icons: 
  image_picker: 
  flutter_tap_payment:
  change_app_package_name:
  fl_toast:
 
  cool_alert:
  flutter_native_splash:
  flutter_credit_card:
  expandable:
  checkbox_formfield:
  youtube_player_flutter:
  stylish_dialog:
  prompt_dialog:
  dialog:
  circular_profile_avatar:
  video_player:
  google_fonts:
  font_awesome_flutter:
  intl_phone_field:
  geolocator:
  latlong2:
  sqflite:
  flutter_map:
  provider:
  url_launcher: 
  http: 
  otp_text_field: 
  flutter_spinkit: 
  introduction_screen: 
  smooth_page_indicator: 
  flag: 
  sizer: 
  snippet_coder_utils: 
  google_maps_flutter: 
  flutter_rating_bar: 
  dropdown_button2: 


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  image: 'assets/images/Screenshot_15.jpg'

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

